### PR TITLE
Fix d.ts export

### LINKED ISSUE #7: Typescript export type is incorrect
It currently says `export default init`. This doesn't match the actual .js code, which uses `module.exports = init` pattern. As a result, it's not possible in a .ts file to correctly import and use the jest-fail-on-console module, without having a type assertion (`as any`).

A proper TS annotation for that would look like
```
export = init;
```
And then a consumer would import it like that:
```
import init = require('jest-fail-on-console')
```
Docs: https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

Thanks!

### PR DESCRIPTION
**Pull request by ValentinH**
Close #7

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -14,4 +14,4 @@ export type InitOptions = {
 }
 declare function init(options?: InitOptions): void
 
-export default init
+export = init
```
Comment (amakhrov) [inline index.d.ts:17]: this won't compile: you can't have both `export type InitOptions` and `export = ` in the same file:
```
TS2309: An export assignment cannot be used in a module with other exported elements.
```

A solution is to wrap the definitions you want to export into a namespace with the same name as what you export via `export =`:
```
declare namespace init {
   // your types here
}

declare function init (...)

export = init
```
